# Use the official Python base image
FROM python:3.8

# Set the working directory inside the container
WORKDIR /api

# Copy the requirements file to the working directory
COPY requirements.txt /api

# Install the Python dependencies
RUN pip install -r requirements.txt

# Copy the application code to the working directory
COPY . .

# Expose the port on which the application will run
EXPOSE 80

# Run the FastAPI application using uvicorn server
CMD ["uvicorn", "main:createApp", "--host", "0.0.0.0", "--port", "80"]